export const UPDATE_USER_LOGIN = "UPDATE_USER_Login";
export const UPDATE_USER_ACCESS_TOKEN = "UPDATE_USER_ACCESS_TOKEN";

export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_COUNTER = "UPDATE_COUNTER";

export const UPDATE_SPEECH = "UPDATE_SPEECH";